package pack.qualy_pro.models;
// Generated 11 janv. 2017 14:16:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private int idClient;
	private String nom;
	private String adresse;
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Client() {
	}

	public Client(int idClient) {
		this.idClient = idClient;
	}

	public Client(int idClient, String nom, String adresse,
			Set<Facture> factures) {
		this.idClient = idClient;
		this.nom = nom;
		this.adresse = adresse;
		this.factures = factures;
	}

	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
