package pack.qualy_pro.models;
// Generated 11 janv. 2017 14:16:40 by Hibernate Tools 3.4.0.CR1

/**
 * DetailsFactprod generated by hbm2java
 */
public class DetailsFactprod implements java.io.Serializable {

	private DetailsFactprodId id;
	private Facture facture;
	private Produit produit;

	public DetailsFactprod() {
	}

	public DetailsFactprod(DetailsFactprodId id) {
		this.id = id;
	}

	public DetailsFactprod(DetailsFactprodId id, Facture facture,
			Produit produit) {
		this.id = id;
		this.facture = facture;
		this.produit = produit;
	}

	public DetailsFactprodId getId() {
		return this.id;
	}

	public void setId(DetailsFactprodId id) {
		this.id = id;
	}

	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

}
