package pack.qualy_pro.models;
// Generated 11 janv. 2017 14:16:40 by Hibernate Tools 3.4.0.CR1

/**
 * DetailsFactprodId generated by hbm2java
 */
public class DetailsFactprodId implements java.io.Serializable {

	private Integer idFacture;
	private Integer idProduit;
	private Integer qte;

	public DetailsFactprodId() {
	}

	public DetailsFactprodId(Integer idFacture, Integer idProduit, Integer qte) {
		this.idFacture = idFacture;
		this.idProduit = idProduit;
		this.qte = qte;
	}

	public Integer getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(Integer idFacture) {
		this.idFacture = idFacture;
	}

	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	public Integer getQte() {
		return this.qte;
	}

	public void setQte(Integer qte) {
		this.qte = qte;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailsFactprodId))
			return false;
		DetailsFactprodId castOther = (DetailsFactprodId) other;

		return ((this.getIdFacture() == castOther.getIdFacture()) || (this
				.getIdFacture() != null && castOther.getIdFacture() != null && this
				.getIdFacture().equals(castOther.getIdFacture())))
				&& ((this.getIdProduit() == castOther.getIdProduit()) || (this
						.getIdProduit() != null
						&& castOther.getIdProduit() != null && this
						.getIdProduit().equals(castOther.getIdProduit())))
				&& ((this.getQte() == castOther.getQte()) || (this.getQte() != null
						&& castOther.getQte() != null && this.getQte().equals(
						castOther.getQte())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdFacture() == null ? 0 : this.getIdFacture().hashCode());
		result = 37 * result
				+ (getIdProduit() == null ? 0 : this.getIdProduit().hashCode());
		result = 37 * result
				+ (getQte() == null ? 0 : this.getQte().hashCode());
		return result;
	}

}
