package pack.qualy_pro.models;
// Generated 11 janv. 2017 14:16:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facture generated by hbm2java
 */
public class Facture implements java.io.Serializable {

	private int idFacture;
	private Utilisateur utilisateur;
	private Client client;
	private Date dateFacture;
	private Integer pht;
	private Integer pttc;
	private Set<DetailsFactprod> detailsFactprods = new HashSet<DetailsFactprod>(
			0);

	public Facture() {
	}

	public Facture(int idFacture) {
		this.idFacture = idFacture;
	}

	public Facture(int idFacture, Utilisateur utilisateur, Client client,
			Date dateFacture, Integer pht, Integer pttc,
			Set<DetailsFactprod> detailsFactprods) {
		this.idFacture = idFacture;
		this.utilisateur = utilisateur;
		this.client = client;
		this.dateFacture = dateFacture;
		this.pht = pht;
		this.pttc = pttc;
		this.detailsFactprods = detailsFactprods;
	}

	public int getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(int idFacture) {
		this.idFacture = idFacture;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Date getDateFacture() {
		return this.dateFacture;
	}

	public void setDateFacture(Date dateFacture) {
		this.dateFacture = dateFacture;
	}

	public Integer getPht() {
		return this.pht;
	}

	public void setPht(Integer pht) {
		this.pht = pht;
	}

	public Integer getPttc() {
		return this.pttc;
	}

	public void setPttc(Integer pttc) {
		this.pttc = pttc;
	}

	public Set<DetailsFactprod> getDetailsFactprods() {
		return this.detailsFactprods;
	}

	public void setDetailsFactprods(Set<DetailsFactprod> detailsFactprods) {
		this.detailsFactprods = detailsFactprods;
	}

}
