package pack.qualy_pro.models;
// Generated 11 janv. 2017 14:16:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur implements java.io.Serializable {

	private int idFournisseur;
	private String raisonSociale;
	private String adresse;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Fournisseur() {
	}

	public Fournisseur(int idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	public Fournisseur(int idFournisseur, String raisonSociale, String adresse,
			Set<Produit> produits) {
		this.idFournisseur = idFournisseur;
		this.raisonSociale = raisonSociale;
		this.adresse = adresse;
		this.produits = produits;
	}

	public int getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(int idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	public String getRaisonSociale() {
		return this.raisonSociale;
	}

	public void setRaisonSociale(String raisonSociale) {
		this.raisonSociale = raisonSociale;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
