package pack.qualy_pro.models;
// Generated 11 janv. 2017 14:16:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pavillion generated by hbm2java
 */
public class Pavillion implements java.io.Serializable {

	private int idPavillion;
	private Magasin magasin;
	private String libelle;
	private String description;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Pavillion() {
	}

	public Pavillion(int idPavillion) {
		this.idPavillion = idPavillion;
	}

	public Pavillion(int idPavillion, Magasin magasin, String libelle,
			String description, Set<Produit> produits) {
		this.idPavillion = idPavillion;
		this.magasin = magasin;
		this.libelle = libelle;
		this.description = description;
		this.produits = produits;
	}

	public int getIdPavillion() {
		return this.idPavillion;
	}

	public void setIdPavillion(int idPavillion) {
		this.idPavillion = idPavillion;
	}

	public Magasin getMagasin() {
		return this.magasin;
	}

	public void setMagasin(Magasin magasin) {
		this.magasin = magasin;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
