package pack.qualy_pro.models;
// Generated 11 janv. 2017 14:16:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit implements java.io.Serializable {

	private int idProduit;
	private Pavillion pavillion;
	private Categorie categorie;
	private Fournisseur fournisseur;
	private String nomProd;
	private Integer qteDisponible;
	private String NS;
	private Set<DetailsFactprod> detailsFactprods = new HashSet<DetailsFactprod>(
			0);
	private Set<Prix> prixes = new HashSet<Prix>(0);

	public Produit() {
	}

	public Produit(int idProduit) {
		this.idProduit = idProduit;
	}

	public Produit(int idProduit, Pavillion pavillion, Categorie categorie,
			Fournisseur fournisseur, String nomProd, Integer qteDisponible,
			String NS, Set<DetailsFactprod> detailsFactprods, Set<Prix> prixes) {
		this.idProduit = idProduit;
		this.pavillion = pavillion;
		this.categorie = categorie;
		this.fournisseur = fournisseur;
		this.nomProd = nomProd;
		this.qteDisponible = qteDisponible;
		this.NS = NS;
		this.detailsFactprods = detailsFactprods;
		this.prixes = prixes;
	}

	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	public Pavillion getPavillion() {
		return this.pavillion;
	}

	public void setPavillion(Pavillion pavillion) {
		this.pavillion = pavillion;
	}

	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public String getNomProd() {
		return this.nomProd;
	}

	public void setNomProd(String nomProd) {
		this.nomProd = nomProd;
	}

	public Integer getQteDisponible() {
		return this.qteDisponible;
	}

	public void setQteDisponible(Integer qteDisponible) {
		this.qteDisponible = qteDisponible;
	}

	public String getNS() {
		return this.NS;
	}

	public void setNS(String NS) {
		this.NS = NS;
	}

	public Set<DetailsFactprod> getDetailsFactprods() {
		return this.detailsFactprods;
	}

	public void setDetailsFactprods(Set<DetailsFactprod> detailsFactprods) {
		this.detailsFactprods = detailsFactprods;
	}

	public Set<Prix> getPrixes() {
		return this.prixes;
	}

	public void setPrixes(Set<Prix> prixes) {
		this.prixes = prixes;
	}

}
