package pack.qualy_pro.models;
// Generated 11 janv. 2017 14:16:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private int idUtilisateur;
	private String nom;
	private String prenom;
	private String email;
	private String tel;
	private String adresse;
	private String type;
	private Set<Magasin> magasins = new HashSet<Magasin>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Utilisateur() {
	}

	public Utilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public Utilisateur(int idUtilisateur, String nom, String prenom,
			String email, String tel, String adresse, String type,
			Set<Magasin> magasins, Set<Facture> factures) {
		this.idUtilisateur = idUtilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.tel = tel;
		this.adresse = adresse;
		this.type = type;
		this.magasins = magasins;
		this.factures = factures;
	}

	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<Magasin> getMagasins() {
		return this.magasins;
	}

	public void setMagasins(Set<Magasin> magasins) {
		this.magasins = magasins;
	}

	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
