package pack.qualy_pro.DaoImpl;

// Generated 28 déc. 2016 13:45:48 by Hibernate Tools 3.4.0.CR1

import org.hibernate.SessionFactory;
import pack.qualy_pro.models.*;
import com.IDao.config.DAO;

/**
 * Categorie generated by hbm2java
 */
public class CategorieImpl extends DAO<Categorie>{

	public CategorieImpl(SessionFactory sf) {
		super(sf);
	}

}
